---
spring:
  datasource:
    url: jdbc:sqlserver://host.docker.internal;databaseName=testschema #${msserverdb_endpoint_url} #jdbc:sqlserver://sqlsrv\\sqlexpress;databaseName=customer
    username: test #${msserverdb_endpoint_username}
    password: test #${msserverdb_endpoint_password}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

