---
spring:
  datasource:
    url: ${msserverdb_endpoint_url} #jdbc:sqlserver://localhost;databaseName=testschema
    username: ${msserverdb_endpoint_username} #test
    password: ${msserverdb_endpoint_password} #test
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

